service: rust-lambda-serverless 

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  lambdaHashingVersion: [20201221]


functions:
  hello:
    handler: pkg/rust_lambda.handler
    events:
     - http:
         path: greet
         method: get